// Code generated by MockGen. DO NOT EDIT.
// Source: ./apps/teller/internal/biz/notification.go
//
// Generated by this command:
//
//	mockgen -source=./apps/teller/internal/biz/notification.go -destination=./apps/teller/internal/biz/notification_mock_test.go -package=biz
//

// Package biz is a generated GoMock package.
package biz

import (
	context "context"
	reflect "reflect"
	time "time"

	constant "github.com/toeydevelopment/telltheworld/apps/teller/internal/constant"
	entity "github.com/toeydevelopment/telltheworld/apps/teller/internal/data/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// BulkSave mocks base method.
func (m *MockNotificationRepo) BulkSave(ctx context.Context, notifications []*entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSave", ctx, notifications)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkSave indicates an expected call of BulkSave.
func (mr *MockNotificationRepoMockRecorder) BulkSave(ctx, notifications any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSave", reflect.TypeOf((*MockNotificationRepo)(nil).BulkSave), ctx, notifications)
}

// ClaimNotificationForProcessing mocks base method.
func (m *MockNotificationRepo) ClaimNotificationForProcessing(ctx context.Context, notificationID, workerID string) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNotificationForProcessing", ctx, notificationID, workerID)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNotificationForProcessing indicates an expected call of ClaimNotificationForProcessing.
func (mr *MockNotificationRepoMockRecorder) ClaimNotificationForProcessing(ctx, notificationID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNotificationForProcessing", reflect.TypeOf((*MockNotificationRepo)(nil).ClaimNotificationForProcessing), ctx, notificationID, workerID)
}

// GetByNotificationID mocks base method.
func (m *MockNotificationRepo) GetByNotificationID(ctx context.Context, notificationID string) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNotificationID", ctx, notificationID)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNotificationID indicates an expected call of GetByNotificationID.
func (mr *MockNotificationRepoMockRecorder) GetByNotificationID(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNotificationID", reflect.TypeOf((*MockNotificationRepo)(nil).GetByNotificationID), ctx, notificationID)
}

// PublishNotification mocks base method.
func (m *MockNotificationRepo) PublishNotification(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishNotification", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishNotification indicates an expected call of PublishNotification.
func (mr *MockNotificationRepoMockRecorder) PublishNotification(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishNotification", reflect.TypeOf((*MockNotificationRepo)(nil).PublishNotification), ctx, notification)
}

// ReleaseNotificationFromProcessing mocks base method.
func (m *MockNotificationRepo) ReleaseNotificationFromProcessing(ctx context.Context, notificationID, workerID string, status constant.NotificationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseNotificationFromProcessing", ctx, notificationID, workerID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseNotificationFromProcessing indicates an expected call of ReleaseNotificationFromProcessing.
func (mr *MockNotificationRepoMockRecorder) ReleaseNotificationFromProcessing(ctx, notificationID, workerID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseNotificationFromProcessing", reflect.TypeOf((*MockNotificationRepo)(nil).ReleaseNotificationFromProcessing), ctx, notificationID, workerID, status)
}

// ResetStuckNotifications mocks base method.
func (m *MockNotificationRepo) ResetStuckNotifications(ctx context.Context, stuckAfter time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetStuckNotifications", ctx, stuckAfter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetStuckNotifications indicates an expected call of ResetStuckNotifications.
func (mr *MockNotificationRepoMockRecorder) ResetStuckNotifications(ctx, stuckAfter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetStuckNotifications", reflect.TypeOf((*MockNotificationRepo)(nil).ResetStuckNotifications), ctx, stuckAfter)
}

// Save mocks base method.
func (m *MockNotificationRepo) Save(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockNotificationRepoMockRecorder) Save(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNotificationRepo)(nil).Save), ctx, notification)
}

// SubscribeToNotifications mocks base method.
func (m *MockNotificationRepo) SubscribeToNotifications(ctx context.Context, handler NotificationHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToNotifications", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeToNotifications indicates an expected call of SubscribeToNotifications.
func (mr *MockNotificationRepoMockRecorder) SubscribeToNotifications(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToNotifications", reflect.TypeOf((*MockNotificationRepo)(nil).SubscribeToNotifications), ctx, handler)
}

// UpdateChannelResult mocks base method.
func (m *MockNotificationRepo) UpdateChannelResult(ctx context.Context, notificationID string, channelResult entity.NotificationStatusPerChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannelResult", ctx, notificationID, channelResult)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChannelResult indicates an expected call of UpdateChannelResult.
func (mr *MockNotificationRepoMockRecorder) UpdateChannelResult(ctx, notificationID, channelResult any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannelResult", reflect.TypeOf((*MockNotificationRepo)(nil).UpdateChannelResult), ctx, notificationID, channelResult)
}

// UpdateNotificationWithResults mocks base method.
func (m *MockNotificationRepo) UpdateNotificationWithResults(ctx context.Context, notification *entity.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationWithResults", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationWithResults indicates an expected call of UpdateNotificationWithResults.
func (mr *MockNotificationRepoMockRecorder) UpdateNotificationWithResults(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationWithResults", reflect.TypeOf((*MockNotificationRepo)(nil).UpdateNotificationWithResults), ctx, notification)
}

// UpdateStatus mocks base method.
func (m *MockNotificationRepo) UpdateStatus(ctx context.Context, notificationID string, status constant.NotificationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, notificationID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotificationRepoMockRecorder) UpdateStatus(ctx, notificationID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationRepo)(nil).UpdateStatus), ctx, notificationID, status)
}
