// Code generated by MockGen. DO NOT EDIT.
// Source: ./apps/teller/internal/biz/provider.go
//
// Generated by this command:
//
//	mockgen -source=./apps/teller/internal/biz/provider.go -destination=./apps/teller/internal/biz/provider_mock_test.go -package=biz
//

// Package biz is a generated GoMock package.
package biz

import (
	context "context"
	reflect "reflect"

	constant "github.com/toeydevelopment/telltheworld/apps/teller/internal/constant"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationProvider is a mock of NotificationProvider interface.
type MockNotificationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationProviderMockRecorder
	isgomock struct{}
}

// MockNotificationProviderMockRecorder is the mock recorder for MockNotificationProvider.
type MockNotificationProviderMockRecorder struct {
	mock *MockNotificationProvider
}

// NewMockNotificationProvider creates a new mock instance.
func NewMockNotificationProvider(ctrl *gomock.Controller) *MockNotificationProvider {
	mock := &MockNotificationProvider{ctrl: ctrl}
	mock.recorder = &MockNotificationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationProvider) EXPECT() *MockNotificationProviderMockRecorder {
	return m.recorder
}

// GetChannel mocks base method.
func (m *MockNotificationProvider) GetChannel() constant.NotificationChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel")
	ret0, _ := ret[0].(constant.NotificationChannel)
	return ret0
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockNotificationProviderMockRecorder) GetChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockNotificationProvider)(nil).GetChannel))
}

// Send mocks base method.
func (m *MockNotificationProvider) Send(ctx context.Context, destination, title, body string, metadata map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, destination, title, body, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationProviderMockRecorder) Send(ctx, destination, title, body, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationProvider)(nil).Send), ctx, destination, title, body, metadata)
}
