// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/biz"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/conf"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/data"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/server"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/service"
	"github.com/toeydevelopment/telltheworld/pkg/healthcheck"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "time/tzdata"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, pubSubConfig *conf.PubSubConfig, logger log.Logger) (*kratos.App, func(), error) {
	config, err := data.NewGORMConfig(confData)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := data.NewGORM(config)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(db)
	pubSub, cleanup2, err := data.NewPubSub(pubSubConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationRepo := data.NewNotificationRepo(dataData, pubSub, logger)
	notification := biz.NewNotification(notificationRepo, logger)
	serviceNotification := service.NewNotification(notification, logger)
	v := data.NewHealthZ(db)
	healthcheckService := healthcheck.NewService(logger, v...)
	grpcServer := server.NewGRPCServer(confServer, serviceNotification, healthcheckService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
