// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/toeydevelopment/telltheworld/apps/ecommerce/internal/biz"
	"github.com/toeydevelopment/telltheworld/apps/ecommerce/internal/conf"
	"github.com/toeydevelopment/telltheworld/apps/ecommerce/internal/data"
	"github.com/toeydevelopment/telltheworld/apps/ecommerce/internal/server"
	"github.com/toeydevelopment/telltheworld/apps/ecommerce/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, tellerClient *conf.TellerClient, logger log.Logger) (*kratos.App, func(), error) {
	commerceRepo, cleanup, err := data.NewCommerceRepo(tellerClient, logger)
	if err != nil {
		return nil, nil, err
	}
	ecommerceUsecase := biz.NewEcommerceUsecase(commerceRepo, logger)
	ecommerceService := service.NewEcommerceService(ecommerceUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, ecommerceService, logger)
	httpServer := server.NewHTTPServer(confServer, ecommerceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
