// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.4.0
// - protoc             v3.19.4
// source: healthcheck.proto

package healthcheck

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHealthCheckServiceHealthzCheck = "/pkg.healthcheck.HealthCheckService/HealthzCheck"
const OperationHealthCheckServicePingCheck = "/pkg.healthcheck.HealthCheckService/PingCheck"

type HealthCheckServiceHTTPServer interface {
	HealthzCheck(context.Context, *HealthzCheckRequest) (*HealthzCheckReply, error)
	PingCheck(context.Context, *PingCheckRequest) (*PingCheckReply, error)
}

func RegisterHealthCheckServiceHTTPServer(s *http.Server, srv HealthCheckServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/ping", _HealthCheckService_PingCheck0_HTTP_Handler(srv))
	r.GET("/healthz", _HealthCheckService_HealthzCheck0_HTTP_Handler(srv))
}

func _HealthCheckService_PingCheck0_HTTP_Handler(srv HealthCheckServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthCheckServicePingCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PingCheck(ctx, req.(*PingCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingCheckReply)
		return ctx.Result(200, reply)
	}
}

func _HealthCheckService_HealthzCheck0_HTTP_Handler(srv HealthCheckServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthzCheckRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthCheckServiceHealthzCheck)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HealthzCheck(ctx, req.(*HealthzCheckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthzCheckReply)
		return ctx.Result(200, reply)
	}
}

type HealthCheckServiceHTTPClient interface {
	HealthzCheck(ctx context.Context, req *HealthzCheckRequest, opts ...http.CallOption) (rsp *HealthzCheckReply, err error)
	PingCheck(ctx context.Context, req *PingCheckRequest, opts ...http.CallOption) (rsp *PingCheckReply, err error)
}

type HealthCheckServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthCheckServiceHTTPClient(client *http.Client) HealthCheckServiceHTTPClient {
	return &HealthCheckServiceHTTPClientImpl{client}
}

func (c *HealthCheckServiceHTTPClientImpl) HealthzCheck(ctx context.Context, in *HealthzCheckRequest, opts ...http.CallOption) (*HealthzCheckReply, error) {
	var out HealthzCheckReply
	pattern := "/healthz"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthCheckServiceHealthzCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HealthCheckServiceHTTPClientImpl) PingCheck(ctx context.Context, in *PingCheckRequest, opts ...http.CallOption) (*PingCheckReply, error) {
	var out PingCheckReply
	pattern := "/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHealthCheckServicePingCheck))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
