// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/biz"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/conf"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/data"
	"github.com/toeydevelopment/telltheworld/apps/teller/internal/worker"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "time/tzdata"
)

// Injectors from wire.go:

// wireWorker init worker application.
func wireWorker(confData *conf.Data, pubSubConfig *conf.PubSubConfig, logger log.Logger) (*worker.Worker, func(), error) {
	config, err := data.NewGORMConfig(confData)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := data.NewGORM(config)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(db)
	pubSub, cleanup2, err := data.NewPubSub(pubSubConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationRepo := data.NewNotificationRepo(dataData, pubSub, logger)
	providerRegistry := biz.NewProviderRegistryWithProviders(logger)
	notificationWorker := biz.NewNotificationWorker(notificationRepo, providerRegistry, logger)
	workerWorker := worker.NewWorker(notificationWorker, logger)
	return workerWorker, func() {
		cleanup2()
		cleanup()
	}, nil
}
