// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.32.0
// source: v1/ecommerce.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationEcommerceServiceSendChatMessage = "/ecommerce.v1.EcommerceService/SendChatMessage"
const OperationEcommerceServiceSendPaymentReminder = "/ecommerce.v1.EcommerceService/SendPaymentReminder"
const OperationEcommerceServiceSendShippingUpdate = "/ecommerce.v1.EcommerceService/SendShippingUpdate"
const OperationEcommerceServiceTriggerPurchase = "/ecommerce.v1.EcommerceService/TriggerPurchase"

type EcommerceServiceHTTPServer interface {
	// SendChatMessage Simulate chat message event
	SendChatMessage(context.Context, *SendChatMessageRequest) (*SendChatMessageResponse, error)
	// SendPaymentReminder Simulate payment reminder
	SendPaymentReminder(context.Context, *SendPaymentReminderRequest) (*SendPaymentReminderResponse, error)
	// SendShippingUpdate Simulate shipping update
	SendShippingUpdate(context.Context, *SendShippingUpdateRequest) (*SendShippingUpdateResponse, error)
	// TriggerPurchase Simulate purchase event
	TriggerPurchase(context.Context, *TriggerPurchaseRequest) (*TriggerPurchaseResponse, error)
}

func RegisterEcommerceServiceHTTPServer(s *http.Server, srv EcommerceServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/events/chat-message", _EcommerceService_SendChatMessage0_HTTP_Handler(srv))
	r.POST("/api/v1/events/purchase", _EcommerceService_TriggerPurchase0_HTTP_Handler(srv))
	r.POST("/api/v1/events/payment-reminder", _EcommerceService_SendPaymentReminder0_HTTP_Handler(srv))
	r.POST("/api/v1/events/shipping-update", _EcommerceService_SendShippingUpdate0_HTTP_Handler(srv))
}

func _EcommerceService_SendChatMessage0_HTTP_Handler(srv EcommerceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendChatMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcommerceServiceSendChatMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendChatMessage(ctx, req.(*SendChatMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendChatMessageResponse)
		return ctx.Result(200, reply)
	}
}

func _EcommerceService_TriggerPurchase0_HTTP_Handler(srv EcommerceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TriggerPurchaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcommerceServiceTriggerPurchase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TriggerPurchase(ctx, req.(*TriggerPurchaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TriggerPurchaseResponse)
		return ctx.Result(200, reply)
	}
}

func _EcommerceService_SendPaymentReminder0_HTTP_Handler(srv EcommerceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendPaymentReminderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcommerceServiceSendPaymentReminder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendPaymentReminder(ctx, req.(*SendPaymentReminderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendPaymentReminderResponse)
		return ctx.Result(200, reply)
	}
}

func _EcommerceService_SendShippingUpdate0_HTTP_Handler(srv EcommerceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendShippingUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEcommerceServiceSendShippingUpdate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendShippingUpdate(ctx, req.(*SendShippingUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendShippingUpdateResponse)
		return ctx.Result(200, reply)
	}
}

type EcommerceServiceHTTPClient interface {
	// SendChatMessage Simulate chat message event
	SendChatMessage(ctx context.Context, req *SendChatMessageRequest, opts ...http.CallOption) (rsp *SendChatMessageResponse, err error)
	// SendPaymentReminder Simulate payment reminder
	SendPaymentReminder(ctx context.Context, req *SendPaymentReminderRequest, opts ...http.CallOption) (rsp *SendPaymentReminderResponse, err error)
	// SendShippingUpdate Simulate shipping update
	SendShippingUpdate(ctx context.Context, req *SendShippingUpdateRequest, opts ...http.CallOption) (rsp *SendShippingUpdateResponse, err error)
	// TriggerPurchase Simulate purchase event
	TriggerPurchase(ctx context.Context, req *TriggerPurchaseRequest, opts ...http.CallOption) (rsp *TriggerPurchaseResponse, err error)
}

type EcommerceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewEcommerceServiceHTTPClient(client *http.Client) EcommerceServiceHTTPClient {
	return &EcommerceServiceHTTPClientImpl{client}
}

// SendChatMessage Simulate chat message event
func (c *EcommerceServiceHTTPClientImpl) SendChatMessage(ctx context.Context, in *SendChatMessageRequest, opts ...http.CallOption) (*SendChatMessageResponse, error) {
	var out SendChatMessageResponse
	pattern := "/api/v1/events/chat-message"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEcommerceServiceSendChatMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendPaymentReminder Simulate payment reminder
func (c *EcommerceServiceHTTPClientImpl) SendPaymentReminder(ctx context.Context, in *SendPaymentReminderRequest, opts ...http.CallOption) (*SendPaymentReminderResponse, error) {
	var out SendPaymentReminderResponse
	pattern := "/api/v1/events/payment-reminder"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEcommerceServiceSendPaymentReminder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendShippingUpdate Simulate shipping update
func (c *EcommerceServiceHTTPClientImpl) SendShippingUpdate(ctx context.Context, in *SendShippingUpdateRequest, opts ...http.CallOption) (*SendShippingUpdateResponse, error) {
	var out SendShippingUpdateResponse
	pattern := "/api/v1/events/shipping-update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEcommerceServiceSendShippingUpdate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TriggerPurchase Simulate purchase event
func (c *EcommerceServiceHTTPClientImpl) TriggerPurchase(ctx context.Context, in *TriggerPurchaseRequest, opts ...http.CallOption) (*TriggerPurchaseResponse, error) {
	var out TriggerPurchaseResponse
	pattern := "/api/v1/events/purchase"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationEcommerceServiceTriggerPurchase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
