// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: v1/ecommerce.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_CHAT_MESSAGE     EventType = 0
	EventType_PURCHASE         EventType = 1
	EventType_PAYMENT_REMINDER EventType = 2
	EventType_SHIPPING_UPDATE  EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "CHAT_MESSAGE",
		1: "PURCHASE",
		2: "PAYMENT_REMINDER",
		3: "SHIPPING_UPDATE",
	}
	EventType_value = map[string]int32{
		"CHAT_MESSAGE":     0,
		"PURCHASE":         1,
		"PAYMENT_REMINDER": 2,
		"SHIPPING_UPDATE":  3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_ecommerce_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_v1_ecommerce_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{0}
}

type UserType int32

const (
	UserType_BUYER  UserType = 0
	UserType_SELLER UserType = 1
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "BUYER",
		1: "SELLER",
	}
	UserType_value = map[string]int32{
		"BUYER":  0,
		"SELLER": 1,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_ecommerce_proto_enumTypes[1].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_v1_ecommerce_proto_enumTypes[1]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{1}
}

// Chat Message Event
type SendChatMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BuyerId        string                 `protobuf:"bytes,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId       string                 `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendChatMessageRequest) Reset() {
	*x = SendChatMessageRequest{}
	mi := &file_v1_ecommerce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageRequest) ProtoMessage() {}

func (x *SendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*SendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{0}
}

func (x *SendChatMessageRequest) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *SendChatMessageRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *SendChatMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendChatMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type SendChatMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendChatMessageResponse) Reset() {
	*x = SendChatMessageResponse{}
	mi := &file_v1_ecommerce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageResponse) ProtoMessage() {}

func (x *SendChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageResponse.ProtoReflect.Descriptor instead.
func (*SendChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{1}
}

func (x *SendChatMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendChatMessageResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendChatMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Purchase Event
type TriggerPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerId       string                 `protobuf:"bytes,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId      string                 `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Items         []*PurchaseItem        `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerPurchaseRequest) Reset() {
	*x = TriggerPurchaseRequest{}
	mi := &file_v1_ecommerce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPurchaseRequest) ProtoMessage() {}

func (x *TriggerPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPurchaseRequest.ProtoReflect.Descriptor instead.
func (*TriggerPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerPurchaseRequest) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *TriggerPurchaseRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *TriggerPurchaseRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TriggerPurchaseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TriggerPurchaseRequest) GetItems() []*PurchaseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PurchaseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItem) Reset() {
	*x = PurchaseItem{}
	mi := &file_v1_ecommerce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItem) ProtoMessage() {}

func (x *PurchaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItem.ProtoReflect.Descriptor instead.
func (*PurchaseItem) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{3}
}

func (x *PurchaseItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PurchaseItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *PurchaseItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PurchaseItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type TriggerPurchaseResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerPurchaseResponse) Reset() {
	*x = TriggerPurchaseResponse{}
	mi := &file_v1_ecommerce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPurchaseResponse) ProtoMessage() {}

func (x *TriggerPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPurchaseResponse.ProtoReflect.Descriptor instead.
func (*TriggerPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerPurchaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerPurchaseResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *TriggerPurchaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Payment Reminder Event
type SendPaymentReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyerId       string                 `protobuf:"bytes,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountDue     float64                `protobuf:"fixed64,3,opt,name=amount_due,json=amountDue,proto3" json:"amount_due,omitempty"`
	DueDate       string                 `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"` // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPaymentReminderRequest) Reset() {
	*x = SendPaymentReminderRequest{}
	mi := &file_v1_ecommerce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPaymentReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPaymentReminderRequest) ProtoMessage() {}

func (x *SendPaymentReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPaymentReminderRequest.ProtoReflect.Descriptor instead.
func (*SendPaymentReminderRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{5}
}

func (x *SendPaymentReminderRequest) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *SendPaymentReminderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SendPaymentReminderRequest) GetAmountDue() float64 {
	if x != nil {
		return x.AmountDue
	}
	return 0
}

func (x *SendPaymentReminderRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

type SendPaymentReminderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendPaymentReminderResponse) Reset() {
	*x = SendPaymentReminderResponse{}
	mi := &file_v1_ecommerce_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPaymentReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPaymentReminderResponse) ProtoMessage() {}

func (x *SendPaymentReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPaymentReminderResponse.ProtoReflect.Descriptor instead.
func (*SendPaymentReminderResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{6}
}

func (x *SendPaymentReminderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPaymentReminderResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendPaymentReminderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Shipping Update Event
type SendShippingUpdateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BuyerId        string                 `protobuf:"bytes,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,3,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier        string                 `protobuf:"bytes,4,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "shipped", "in_transit", "delivered"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendShippingUpdateRequest) Reset() {
	*x = SendShippingUpdateRequest{}
	mi := &file_v1_ecommerce_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendShippingUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendShippingUpdateRequest) ProtoMessage() {}

func (x *SendShippingUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendShippingUpdateRequest.ProtoReflect.Descriptor instead.
func (*SendShippingUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{7}
}

func (x *SendShippingUpdateRequest) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *SendShippingUpdateRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SendShippingUpdateRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *SendShippingUpdateRequest) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *SendShippingUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendShippingUpdateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendShippingUpdateResponse) Reset() {
	*x = SendShippingUpdateResponse{}
	mi := &file_v1_ecommerce_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendShippingUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendShippingUpdateResponse) ProtoMessage() {}

func (x *SendShippingUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecommerce_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendShippingUpdateResponse.ProtoReflect.Descriptor instead.
func (*SendShippingUpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecommerce_proto_rawDescGZIP(), []int{8}
}

func (x *SendShippingUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendShippingUpdateResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *SendShippingUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_ecommerce_proto protoreflect.FileDescriptor

const file_v1_ecommerce_proto_rawDesc = "" +
	"\n" +
	"\x12v1/ecommerce.proto\x12\fecommerce.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xae\x01\n" +
	"\x16SendChatMessageRequest\x12\"\n" +
	"\bbuyer_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\abuyerId\x12$\n" +
	"\tseller_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bsellerId\x12!\n" +
	"\amessage\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\amessage\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\"v\n" +
	"\x17SendChatMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe0\x01\n" +
	"\x16TriggerPurchaseRequest\x12\"\n" +
	"\bbuyer_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\abuyerId\x12$\n" +
	"\tseller_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bsellerId\x12\"\n" +
	"\border_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aorderId\x12&\n" +
	"\x06amount\x18\x04 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\x120\n" +
	"\x05items\x18\x05 \x03(\v2\x1a.ecommerce.v1.PurchaseItemR\x05items\"\x82\x01\n" +
	"\fPurchaseItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"v\n" +
	"\x17TriggerPurchaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xae\x01\n" +
	"\x1aSendPaymentReminderRequest\x12\"\n" +
	"\bbuyer_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\abuyerId\x12\"\n" +
	"\border_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aorderId\x12-\n" +
	"\n" +
	"amount_due\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\tamountDue\x12\x19\n" +
	"\bdue_date\x18\x04 \x01(\tR\adueDate\"z\n" +
	"\x1bSendPaymentReminderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xbe\x01\n" +
	"\x19SendShippingUpdateRequest\x12\"\n" +
	"\bbuyer_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\abuyerId\x12\"\n" +
	"\border_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aorderId\x12'\n" +
	"\x0ftracking_number\x18\x03 \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\acarrier\x18\x04 \x01(\tR\acarrier\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"y\n" +
	"\x1aSendShippingUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*V\n" +
	"\tEventType\x12\x10\n" +
	"\fCHAT_MESSAGE\x10\x00\x12\f\n" +
	"\bPURCHASE\x10\x01\x12\x14\n" +
	"\x10PAYMENT_REMINDER\x10\x02\x12\x13\n" +
	"\x0fSHIPPING_UPDATE\x10\x03*!\n" +
	"\bUserType\x12\t\n" +
	"\x05BUYER\x10\x00\x12\n" +
	"\n" +
	"\x06SELLER\x10\x012\xce\x04\n" +
	"\x10EcommerceService\x12\x86\x01\n" +
	"\x0fSendChatMessage\x12$.ecommerce.v1.SendChatMessageRequest\x1a%.ecommerce.v1.SendChatMessageResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/events/chat-message\x12\x82\x01\n" +
	"\x0fTriggerPurchase\x12$.ecommerce.v1.TriggerPurchaseRequest\x1a%.ecommerce.v1.TriggerPurchaseResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/events/purchase\x12\x96\x01\n" +
	"\x13SendPaymentReminder\x12(.ecommerce.v1.SendPaymentReminderRequest\x1a).ecommerce.v1.SendPaymentReminderResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/events/payment-reminder\x12\x92\x01\n" +
	"\x12SendShippingUpdate\x12'.ecommerce.v1.SendShippingUpdateRequest\x1a(.ecommerce.v1.SendShippingUpdateResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/events/shipping-updateB7\n" +
	"\x10api.ecommerce.v1P\x01Z!github.com/toeydevelopment/telltheworld/apis/ecommerce/v1;v1b\x06proto3"

var (
	file_v1_ecommerce_proto_rawDescOnce sync.Once
	file_v1_ecommerce_proto_rawDescData []byte
)

func file_v1_ecommerce_proto_rawDescGZIP() []byte {
	file_v1_ecommerce_proto_rawDescOnce.Do(func() {
		file_v1_ecommerce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_ecommerce_proto_rawDesc), len(file_v1_ecommerce_proto_rawDesc)))
	})
	return file_v1_ecommerce_proto_rawDescData
}

var file_v1_ecommerce_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_ecommerce_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_ecommerce_proto_goTypes = []any{
	(EventType)(0),                      // 0: ecommerce.v1.EventType
	(UserType)(0),                       // 1: ecommerce.v1.UserType
	(*SendChatMessageRequest)(nil),      // 2: ecommerce.v1.SendChatMessageRequest
	(*SendChatMessageResponse)(nil),     // 3: ecommerce.v1.SendChatMessageResponse
	(*TriggerPurchaseRequest)(nil),      // 4: ecommerce.v1.TriggerPurchaseRequest
	(*PurchaseItem)(nil),                // 5: ecommerce.v1.PurchaseItem
	(*TriggerPurchaseResponse)(nil),     // 6: ecommerce.v1.TriggerPurchaseResponse
	(*SendPaymentReminderRequest)(nil),  // 7: ecommerce.v1.SendPaymentReminderRequest
	(*SendPaymentReminderResponse)(nil), // 8: ecommerce.v1.SendPaymentReminderResponse
	(*SendShippingUpdateRequest)(nil),   // 9: ecommerce.v1.SendShippingUpdateRequest
	(*SendShippingUpdateResponse)(nil),  // 10: ecommerce.v1.SendShippingUpdateResponse
}
var file_v1_ecommerce_proto_depIdxs = []int32{
	5,  // 0: ecommerce.v1.TriggerPurchaseRequest.items:type_name -> ecommerce.v1.PurchaseItem
	2,  // 1: ecommerce.v1.EcommerceService.SendChatMessage:input_type -> ecommerce.v1.SendChatMessageRequest
	4,  // 2: ecommerce.v1.EcommerceService.TriggerPurchase:input_type -> ecommerce.v1.TriggerPurchaseRequest
	7,  // 3: ecommerce.v1.EcommerceService.SendPaymentReminder:input_type -> ecommerce.v1.SendPaymentReminderRequest
	9,  // 4: ecommerce.v1.EcommerceService.SendShippingUpdate:input_type -> ecommerce.v1.SendShippingUpdateRequest
	3,  // 5: ecommerce.v1.EcommerceService.SendChatMessage:output_type -> ecommerce.v1.SendChatMessageResponse
	6,  // 6: ecommerce.v1.EcommerceService.TriggerPurchase:output_type -> ecommerce.v1.TriggerPurchaseResponse
	8,  // 7: ecommerce.v1.EcommerceService.SendPaymentReminder:output_type -> ecommerce.v1.SendPaymentReminderResponse
	10, // 8: ecommerce.v1.EcommerceService.SendShippingUpdate:output_type -> ecommerce.v1.SendShippingUpdateResponse
	5,  // [5:9] is the sub-list for method output_type
	1,  // [1:5] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_v1_ecommerce_proto_init() }
func file_v1_ecommerce_proto_init() {
	if File_v1_ecommerce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_ecommerce_proto_rawDesc), len(file_v1_ecommerce_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_ecommerce_proto_goTypes,
		DependencyIndexes: file_v1_ecommerce_proto_depIdxs,
		EnumInfos:         file_v1_ecommerce_proto_enumTypes,
		MessageInfos:      file_v1_ecommerce_proto_msgTypes,
	}.Build()
	File_v1_ecommerce_proto = out.File
	file_v1_ecommerce_proto_goTypes = nil
	file_v1_ecommerce_proto_depIdxs = nil
}
