// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/ecommerce.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SendChatMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendChatMessageRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendChatMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendChatMessageRequestMultiError, or nil if none found.
func (m *SendChatMessageRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendChatMessageRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBuyerId()) < 1 {
		err := SendChatMessageRequestValidationError{
			field:  "BuyerId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSellerId()) < 1 {
		err := SendChatMessageRequestValidationError{
			field:  "SellerId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMessage()) < 1 {
		err := SendChatMessageRequestValidationError{
			field:  "Message",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for ConversationId

	if len(errors) > 0 {
		return SendChatMessageRequestMultiError(errors)
	}

	return nil
}

// SendChatMessageRequestMultiError is an error wrapping multiple validation
// errors returned by SendChatMessageRequest.ValidateAll() if the designated
// constraints aren't met.
type SendChatMessageRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendChatMessageRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendChatMessageRequestMultiError) AllErrors() []error { return m }

// SendChatMessageRequestValidationError is the validation error returned by
// SendChatMessageRequest.Validate if the designated constraints aren't met.
type SendChatMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendChatMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendChatMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendChatMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendChatMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendChatMessageRequestValidationError) ErrorName() string {
	return "SendChatMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendChatMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendChatMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendChatMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendChatMessageRequestValidationError{}

// Validate checks the field values on SendChatMessageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendChatMessageResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendChatMessageResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendChatMessageResponseMultiError, or nil if none found.
func (m *SendChatMessageResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendChatMessageResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for NotificationId

	// no validation rules for Message

	if len(errors) > 0 {
		return SendChatMessageResponseMultiError(errors)
	}

	return nil
}

// SendChatMessageResponseMultiError is an error wrapping multiple validation
// errors returned by SendChatMessageResponse.ValidateAll() if the designated
// constraints aren't met.
type SendChatMessageResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendChatMessageResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendChatMessageResponseMultiError) AllErrors() []error { return m }

// SendChatMessageResponseValidationError is the validation error returned by
// SendChatMessageResponse.Validate if the designated constraints aren't met.
type SendChatMessageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendChatMessageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendChatMessageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendChatMessageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendChatMessageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendChatMessageResponseValidationError) ErrorName() string {
	return "SendChatMessageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendChatMessageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendChatMessageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendChatMessageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendChatMessageResponseValidationError{}

// Validate checks the field values on TriggerPurchaseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TriggerPurchaseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerPurchaseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerPurchaseRequestMultiError, or nil if none found.
func (m *TriggerPurchaseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerPurchaseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBuyerId()) < 1 {
		err := TriggerPurchaseRequestValidationError{
			field:  "BuyerId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSellerId()) < 1 {
		err := TriggerPurchaseRequestValidationError{
			field:  "SellerId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrderId()) < 1 {
		err := TriggerPurchaseRequestValidationError{
			field:  "OrderId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := TriggerPurchaseRequestValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TriggerPurchaseRequestValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TriggerPurchaseRequestValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TriggerPurchaseRequestValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TriggerPurchaseRequestMultiError(errors)
	}

	return nil
}

// TriggerPurchaseRequestMultiError is an error wrapping multiple validation
// errors returned by TriggerPurchaseRequest.ValidateAll() if the designated
// constraints aren't met.
type TriggerPurchaseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerPurchaseRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerPurchaseRequestMultiError) AllErrors() []error { return m }

// TriggerPurchaseRequestValidationError is the validation error returned by
// TriggerPurchaseRequest.Validate if the designated constraints aren't met.
type TriggerPurchaseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerPurchaseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerPurchaseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerPurchaseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerPurchaseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerPurchaseRequestValidationError) ErrorName() string {
	return "TriggerPurchaseRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerPurchaseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerPurchaseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerPurchaseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerPurchaseRequestValidationError{}

// Validate checks the field values on PurchaseItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PurchaseItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PurchaseItemMultiError, or
// nil if none found.
func (m *PurchaseItem) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	// no validation rules for ProductName

	// no validation rules for Quantity

	// no validation rules for Price

	if len(errors) > 0 {
		return PurchaseItemMultiError(errors)
	}

	return nil
}

// PurchaseItemMultiError is an error wrapping multiple validation errors
// returned by PurchaseItem.ValidateAll() if the designated constraints aren't met.
type PurchaseItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseItemMultiError) AllErrors() []error { return m }

// PurchaseItemValidationError is the validation error returned by
// PurchaseItem.Validate if the designated constraints aren't met.
type PurchaseItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseItemValidationError) ErrorName() string { return "PurchaseItemValidationError" }

// Error satisfies the builtin error interface
func (e PurchaseItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseItemValidationError{}

// Validate checks the field values on TriggerPurchaseResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TriggerPurchaseResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerPurchaseResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerPurchaseResponseMultiError, or nil if none found.
func (m *TriggerPurchaseResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerPurchaseResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for NotificationId

	// no validation rules for Message

	if len(errors) > 0 {
		return TriggerPurchaseResponseMultiError(errors)
	}

	return nil
}

// TriggerPurchaseResponseMultiError is an error wrapping multiple validation
// errors returned by TriggerPurchaseResponse.ValidateAll() if the designated
// constraints aren't met.
type TriggerPurchaseResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerPurchaseResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerPurchaseResponseMultiError) AllErrors() []error { return m }

// TriggerPurchaseResponseValidationError is the validation error returned by
// TriggerPurchaseResponse.Validate if the designated constraints aren't met.
type TriggerPurchaseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerPurchaseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerPurchaseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerPurchaseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerPurchaseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerPurchaseResponseValidationError) ErrorName() string {
	return "TriggerPurchaseResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerPurchaseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerPurchaseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerPurchaseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerPurchaseResponseValidationError{}

// Validate checks the field values on SendPaymentReminderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendPaymentReminderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendPaymentReminderRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendPaymentReminderRequestMultiError, or nil if none found.
func (m *SendPaymentReminderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendPaymentReminderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBuyerId()) < 1 {
		err := SendPaymentReminderRequestValidationError{
			field:  "BuyerId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrderId()) < 1 {
		err := SendPaymentReminderRequestValidationError{
			field:  "OrderId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmountDue() <= 0 {
		err := SendPaymentReminderRequestValidationError{
			field:  "AmountDue",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for DueDate

	if len(errors) > 0 {
		return SendPaymentReminderRequestMultiError(errors)
	}

	return nil
}

// SendPaymentReminderRequestMultiError is an error wrapping multiple
// validation errors returned by SendPaymentReminderRequest.ValidateAll() if
// the designated constraints aren't met.
type SendPaymentReminderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendPaymentReminderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendPaymentReminderRequestMultiError) AllErrors() []error { return m }

// SendPaymentReminderRequestValidationError is the validation error returned
// by SendPaymentReminderRequest.Validate if the designated constraints aren't met.
type SendPaymentReminderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendPaymentReminderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendPaymentReminderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendPaymentReminderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendPaymentReminderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendPaymentReminderRequestValidationError) ErrorName() string {
	return "SendPaymentReminderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendPaymentReminderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendPaymentReminderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendPaymentReminderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendPaymentReminderRequestValidationError{}

// Validate checks the field values on SendPaymentReminderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendPaymentReminderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendPaymentReminderResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendPaymentReminderResponseMultiError, or nil if none found.
func (m *SendPaymentReminderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendPaymentReminderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for NotificationId

	// no validation rules for Message

	if len(errors) > 0 {
		return SendPaymentReminderResponseMultiError(errors)
	}

	return nil
}

// SendPaymentReminderResponseMultiError is an error wrapping multiple
// validation errors returned by SendPaymentReminderResponse.ValidateAll() if
// the designated constraints aren't met.
type SendPaymentReminderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendPaymentReminderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendPaymentReminderResponseMultiError) AllErrors() []error { return m }

// SendPaymentReminderResponseValidationError is the validation error returned
// by SendPaymentReminderResponse.Validate if the designated constraints
// aren't met.
type SendPaymentReminderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendPaymentReminderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendPaymentReminderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendPaymentReminderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendPaymentReminderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendPaymentReminderResponseValidationError) ErrorName() string {
	return "SendPaymentReminderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendPaymentReminderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendPaymentReminderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendPaymentReminderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendPaymentReminderResponseValidationError{}

// Validate checks the field values on SendShippingUpdateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendShippingUpdateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendShippingUpdateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendShippingUpdateRequestMultiError, or nil if none found.
func (m *SendShippingUpdateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendShippingUpdateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBuyerId()) < 1 {
		err := SendShippingUpdateRequestValidationError{
			field:  "BuyerId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrderId()) < 1 {
		err := SendShippingUpdateRequestValidationError{
			field:  "OrderId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for TrackingNumber

	// no validation rules for Carrier

	// no validation rules for Status

	if len(errors) > 0 {
		return SendShippingUpdateRequestMultiError(errors)
	}

	return nil
}

// SendShippingUpdateRequestMultiError is an error wrapping multiple validation
// errors returned by SendShippingUpdateRequest.ValidateAll() if the
// designated constraints aren't met.
type SendShippingUpdateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendShippingUpdateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendShippingUpdateRequestMultiError) AllErrors() []error { return m }

// SendShippingUpdateRequestValidationError is the validation error returned by
// SendShippingUpdateRequest.Validate if the designated constraints aren't met.
type SendShippingUpdateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendShippingUpdateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendShippingUpdateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendShippingUpdateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendShippingUpdateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendShippingUpdateRequestValidationError) ErrorName() string {
	return "SendShippingUpdateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendShippingUpdateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendShippingUpdateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendShippingUpdateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendShippingUpdateRequestValidationError{}

// Validate checks the field values on SendShippingUpdateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendShippingUpdateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendShippingUpdateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendShippingUpdateResponseMultiError, or nil if none found.
func (m *SendShippingUpdateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendShippingUpdateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for NotificationId

	// no validation rules for Message

	if len(errors) > 0 {
		return SendShippingUpdateResponseMultiError(errors)
	}

	return nil
}

// SendShippingUpdateResponseMultiError is an error wrapping multiple
// validation errors returned by SendShippingUpdateResponse.ValidateAll() if
// the designated constraints aren't met.
type SendShippingUpdateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendShippingUpdateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendShippingUpdateResponseMultiError) AllErrors() []error { return m }

// SendShippingUpdateResponseValidationError is the validation error returned
// by SendShippingUpdateResponse.Validate if the designated constraints aren't met.
type SendShippingUpdateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendShippingUpdateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendShippingUpdateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendShippingUpdateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendShippingUpdateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendShippingUpdateResponseValidationError) ErrorName() string {
	return "SendShippingUpdateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendShippingUpdateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendShippingUpdateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendShippingUpdateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendShippingUpdateResponseValidationError{}
