// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: v1/ecommerce.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EcommerceService_SendChatMessage_FullMethodName     = "/ecommerce.v1.EcommerceService/SendChatMessage"
	EcommerceService_TriggerPurchase_FullMethodName     = "/ecommerce.v1.EcommerceService/TriggerPurchase"
	EcommerceService_SendPaymentReminder_FullMethodName = "/ecommerce.v1.EcommerceService/SendPaymentReminder"
	EcommerceService_SendShippingUpdate_FullMethodName  = "/ecommerce.v1.EcommerceService/SendShippingUpdate"
)

// EcommerceServiceClient is the client API for EcommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcommerceServiceClient interface {
	// Simulate chat message event
	SendChatMessage(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (*SendChatMessageResponse, error)
	// Simulate purchase event
	TriggerPurchase(ctx context.Context, in *TriggerPurchaseRequest, opts ...grpc.CallOption) (*TriggerPurchaseResponse, error)
	// Simulate payment reminder
	SendPaymentReminder(ctx context.Context, in *SendPaymentReminderRequest, opts ...grpc.CallOption) (*SendPaymentReminderResponse, error)
	// Simulate shipping update
	SendShippingUpdate(ctx context.Context, in *SendShippingUpdateRequest, opts ...grpc.CallOption) (*SendShippingUpdateResponse, error)
}

type ecommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcommerceServiceClient(cc grpc.ClientConnInterface) EcommerceServiceClient {
	return &ecommerceServiceClient{cc}
}

func (c *ecommerceServiceClient) SendChatMessage(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (*SendChatMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatMessageResponse)
	err := c.cc.Invoke(ctx, EcommerceService_SendChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) TriggerPurchase(ctx context.Context, in *TriggerPurchaseRequest, opts ...grpc.CallOption) (*TriggerPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerPurchaseResponse)
	err := c.cc.Invoke(ctx, EcommerceService_TriggerPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) SendPaymentReminder(ctx context.Context, in *SendPaymentReminderRequest, opts ...grpc.CallOption) (*SendPaymentReminderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPaymentReminderResponse)
	err := c.cc.Invoke(ctx, EcommerceService_SendPaymentReminder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) SendShippingUpdate(ctx context.Context, in *SendShippingUpdateRequest, opts ...grpc.CallOption) (*SendShippingUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendShippingUpdateResponse)
	err := c.cc.Invoke(ctx, EcommerceService_SendShippingUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcommerceServiceServer is the server API for EcommerceService service.
// All implementations must embed UnimplementedEcommerceServiceServer
// for forward compatibility.
type EcommerceServiceServer interface {
	// Simulate chat message event
	SendChatMessage(context.Context, *SendChatMessageRequest) (*SendChatMessageResponse, error)
	// Simulate purchase event
	TriggerPurchase(context.Context, *TriggerPurchaseRequest) (*TriggerPurchaseResponse, error)
	// Simulate payment reminder
	SendPaymentReminder(context.Context, *SendPaymentReminderRequest) (*SendPaymentReminderResponse, error)
	// Simulate shipping update
	SendShippingUpdate(context.Context, *SendShippingUpdateRequest) (*SendShippingUpdateResponse, error)
	mustEmbedUnimplementedEcommerceServiceServer()
}

// UnimplementedEcommerceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEcommerceServiceServer struct{}

func (UnimplementedEcommerceServiceServer) SendChatMessage(context.Context, *SendChatMessageRequest) (*SendChatMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChatMessage not implemented")
}
func (UnimplementedEcommerceServiceServer) TriggerPurchase(context.Context, *TriggerPurchaseRequest) (*TriggerPurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerPurchase not implemented")
}
func (UnimplementedEcommerceServiceServer) SendPaymentReminder(context.Context, *SendPaymentReminderRequest) (*SendPaymentReminderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPaymentReminder not implemented")
}
func (UnimplementedEcommerceServiceServer) SendShippingUpdate(context.Context, *SendShippingUpdateRequest) (*SendShippingUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendShippingUpdate not implemented")
}
func (UnimplementedEcommerceServiceServer) mustEmbedUnimplementedEcommerceServiceServer() {}
func (UnimplementedEcommerceServiceServer) testEmbeddedByValue()                          {}

// UnsafeEcommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcommerceServiceServer will
// result in compilation errors.
type UnsafeEcommerceServiceServer interface {
	mustEmbedUnimplementedEcommerceServiceServer()
}

func RegisterEcommerceServiceServer(s grpc.ServiceRegistrar, srv EcommerceServiceServer) {
	// If the following call pancis, it indicates UnimplementedEcommerceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EcommerceService_ServiceDesc, srv)
}

func _EcommerceService_SendChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).SendChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_SendChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).SendChatMessage(ctx, req.(*SendChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_TriggerPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).TriggerPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_TriggerPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).TriggerPurchase(ctx, req.(*TriggerPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_SendPaymentReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPaymentReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).SendPaymentReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_SendPaymentReminder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).SendPaymentReminder(ctx, req.(*SendPaymentReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_SendShippingUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendShippingUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).SendShippingUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_SendShippingUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).SendShippingUpdate(ctx, req.(*SendShippingUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EcommerceService_ServiceDesc is the grpc.ServiceDesc for EcommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.v1.EcommerceService",
	HandlerType: (*EcommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendChatMessage",
			Handler:    _EcommerceService_SendChatMessage_Handler,
		},
		{
			MethodName: "TriggerPurchase",
			Handler:    _EcommerceService_TriggerPurchase_Handler,
		},
		{
			MethodName: "SendPaymentReminder",
			Handler:    _EcommerceService_SendPaymentReminder_Handler,
		},
		{
			MethodName: "SendShippingUpdate",
			Handler:    _EcommerceService_SendShippingUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/ecommerce.proto",
}
