// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknown(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_UNKNOWN.String() && e.Code == 500
}

func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorCode_UNKNOWN.String(), fmt.Sprintf(format, args...))
}

func IsInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_INVALID_REQUEST.String() && e.Code == 400
}

func ErrorInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorCode_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorCode_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsOrderNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_ORDER_NOT_FOUND.String() && e.Code == 404
}

func ErrorOrderNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorCode_ORDER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsNotificationFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_NOTIFICATION_FAILED.String() && e.Code == 500
}

func ErrorNotificationFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorCode_NOTIFICATION_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsTellerServiceUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorCode_TELLER_SERVICE_UNAVAILABLE.String() && e.Code == 503
}

func ErrorTellerServiceUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorCode_TELLER_SERVICE_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}
