// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: v1/ecommerce_error.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_UNKNOWN                    ErrorCode = 0
	ErrorCode_INVALID_REQUEST            ErrorCode = 1
	ErrorCode_USER_NOT_FOUND             ErrorCode = 2
	ErrorCode_ORDER_NOT_FOUND            ErrorCode = 3
	ErrorCode_NOTIFICATION_FAILED        ErrorCode = 4
	ErrorCode_TELLER_SERVICE_UNAVAILABLE ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "INVALID_REQUEST",
		2: "USER_NOT_FOUND",
		3: "ORDER_NOT_FOUND",
		4: "NOTIFICATION_FAILED",
		5: "TELLER_SERVICE_UNAVAILABLE",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":                    0,
		"INVALID_REQUEST":            1,
		"USER_NOT_FOUND":             2,
		"ORDER_NOT_FOUND":            3,
		"NOTIFICATION_FAILED":        4,
		"TELLER_SERVICE_UNAVAILABLE": 5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_ecommerce_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_v1_ecommerce_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_v1_ecommerce_error_proto_rawDescGZIP(), []int{0}
}

var File_v1_ecommerce_error_proto protoreflect.FileDescriptor

const file_v1_ecommerce_error_proto_rawDesc = "" +
	"\n" +
	"\x18v1/ecommerce_error.proto\x12\fecommerce.v1\x1a\x13errors/errors.proto*\xb9\x01\n" +
	"\tErrorCode\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x19\n" +
	"\x0fINVALID_REQUEST\x10\x01\x1a\x04\xa8E\x90\x03\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x02\x1a\x04\xa8E\x94\x03\x12\x19\n" +
	"\x0fORDER_NOT_FOUND\x10\x03\x1a\x04\xa8E\x94\x03\x12\x1d\n" +
	"\x13NOTIFICATION_FAILED\x10\x04\x1a\x04\xa8E\xf4\x03\x12$\n" +
	"\x1aTELLER_SERVICE_UNAVAILABLE\x10\x05\x1a\x04\xa8E\xf7\x03\x1a\x04\xa0E\xf4\x03B7\n" +
	"\x10api.ecommerce.v1P\x01Z!github.com/toeydevelopment/telltheworld/apis/ecommerce/v1;v1b\x06proto3"

var (
	file_v1_ecommerce_error_proto_rawDescOnce sync.Once
	file_v1_ecommerce_error_proto_rawDescData []byte
)

func file_v1_ecommerce_error_proto_rawDescGZIP() []byte {
	file_v1_ecommerce_error_proto_rawDescOnce.Do(func() {
		file_v1_ecommerce_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_ecommerce_error_proto_rawDesc), len(file_v1_ecommerce_error_proto_rawDesc)))
	})
	return file_v1_ecommerce_error_proto_rawDescData
}

var file_v1_ecommerce_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_ecommerce_error_proto_goTypes = []any{
	(ErrorCode)(0), // 0: ecommerce.v1.ErrorCode
}
var file_v1_ecommerce_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_ecommerce_error_proto_init() }
func file_v1_ecommerce_error_proto_init() {
	if File_v1_ecommerce_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_ecommerce_error_proto_rawDesc), len(file_v1_ecommerce_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_ecommerce_error_proto_goTypes,
		DependencyIndexes: file_v1_ecommerce_error_proto_depIdxs,
		EnumInfos:         file_v1_ecommerce_error_proto_enumTypes,
	}.Build()
	File_v1_ecommerce_error_proto = out.File
	file_v1_ecommerce_error_proto_goTypes = nil
	file_v1_ecommerce_error_proto_depIdxs = nil
}
