// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: v1/notification.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationChannel int32

const (
	NotificationChannel_NotificationChannel_Unknown NotificationChannel = 0
	NotificationChannel_NotificationChannel_Push    NotificationChannel = 1
	NotificationChannel_NotificationChannel_Email   NotificationChannel = 2
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NotificationChannel_Unknown",
		1: "NotificationChannel_Push",
		2: "NotificationChannel_Email",
	}
	NotificationChannel_value = map[string]int32{
		"NotificationChannel_Unknown": 0,
		"NotificationChannel_Push":    1,
		"NotificationChannel_Email":   2,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_v1_notification_proto_enumTypes[0]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationStatus int32

const (
	NotificationStatus_NotificationStatus_Unknown NotificationStatus = 0
	NotificationStatus_NotificationStatus_Pending NotificationStatus = 1
	NotificationStatus_NotificationStatus_Sent    NotificationStatus = 2
	NotificationStatus_NotificationStatus_Failed  NotificationStatus = 3
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NotificationStatus_Unknown",
		1: "NotificationStatus_Pending",
		2: "NotificationStatus_Sent",
		3: "NotificationStatus_Failed",
	}
	NotificationStatus_value = map[string]int32{
		"NotificationStatus_Unknown": 0,
		"NotificationStatus_Pending": 1,
		"NotificationStatus_Sent":    2,
		"NotificationStatus_Failed":  3,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_v1_notification_proto_enumTypes[1]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{1}
}

type Notification struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Title    string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body     string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	RefId    string                 `protobuf:"bytes,3,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Channels []NotificationChannel  `protobuf:"varint,4,rep,packed,name=channels,proto3,enum=teller.v1.NotificationChannel" json:"channels,omitempty"`
	// google.protobuf.Timestamp created_at = 4 [json_name = "created_at"];
	// google.protobuf.Timestamp send_at = 5 [json_name = "send_at"];
	ScheduleAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=schedule_at,proto3,oneof" json:"schedule_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *Notification) GetChannels() []NotificationChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *Notification) GetScheduleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleAt
	}
	return nil
}

type StatusPerChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       NotificationChannel    `protobuf:"varint,1,opt,name=channel,proto3,enum=teller.v1.NotificationChannel" json:"channel,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=teller.v1.NotificationStatus" json:"status,omitempty"`
	FailReason    *string                `protobuf:"bytes,3,opt,name=fail_reason,json=failReason,proto3,oneof" json:"fail_reason,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusPerChannel) Reset() {
	*x = StatusPerChannel{}
	mi := &file_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusPerChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusPerChannel) ProtoMessage() {}

func (x *StatusPerChannel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusPerChannel.ProtoReflect.Descriptor instead.
func (*StatusPerChannel) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *StatusPerChannel) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NotificationChannel_Unknown
}

func (x *StatusPerChannel) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NotificationStatus_Unknown
}

func (x *StatusPerChannel) GetFailReason() string {
	if x != nil && x.FailReason != nil {
		return *x.FailReason
	}
	return ""
}

func (x *StatusPerChannel) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type WillPushReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WillPushReply) Reset() {
	*x = WillPushReply{}
	mi := &file_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WillPushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WillPushReply) ProtoMessage() {}

func (x *WillPushReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WillPushReply.ProtoReflect.Descriptor instead.
func (*WillPushReply) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *WillPushReply) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type BoardcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardcastRequest) Reset() {
	*x = BoardcastRequest{}
	mi := &file_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardcastRequest) ProtoMessage() {}

func (x *BoardcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardcastRequest.ProtoReflect.Descriptor instead.
func (*BoardcastRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *BoardcastRequest) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ChannelDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       NotificationChannel    `protobuf:"varint,1,opt,name=channel,proto3,enum=teller.v1.NotificationChannel" json:"channel,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelDestination) Reset() {
	*x = ChannelDestination{}
	mi := &file_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelDestination) ProtoMessage() {}

func (x *ChannelDestination) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelDestination.ProtoReflect.Descriptor instead.
func (*ChannelDestination) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelDestination) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NotificationChannel_Unknown
}

func (x *ChannelDestination) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type SendToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	Destinations  []*ChannelDestination  `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUserRequest) Reset() {
	*x = SendToUserRequest{}
	mi := &file_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserRequest) ProtoMessage() {}

func (x *SendToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserRequest.ProtoReflect.Descriptor instead.
func (*SendToUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SendToUserRequest) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *SendToUserRequest) GetDestinations() []*ChannelDestination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type BulkSendToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*SendToUserRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSendToUserRequest) Reset() {
	*x = BulkSendToUserRequest{}
	mi := &file_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSendToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSendToUserRequest) ProtoMessage() {}

func (x *BulkSendToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSendToUserRequest.ProtoReflect.Descriptor instead.
func (*BulkSendToUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *BulkSendToUserRequest) GetRequests() []*SendToUserRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BulkSendToUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*WillPushReply       `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkSendToUserReply) Reset() {
	*x = BulkSendToUserReply{}
	mi := &file_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkSendToUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkSendToUserReply) ProtoMessage() {}

func (x *BulkSendToUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkSendToUserReply.ProtoReflect.Descriptor instead.
func (*BulkSendToUserReply) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *BulkSendToUserReply) GetReplies() []*WillPushReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

type GetNotificationStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotificationStatusRequest) Reset() {
	*x = GetNotificationStatusRequest{}
	mi := &file_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusRequest) ProtoMessage() {}

func (x *GetNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetNotificationStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetNotificationStatusReply struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Statuses      []*GetNotificationStatusReply_StatusPerChannel `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationStatusReply) Reset() {
	*x = GetNotificationStatusReply{}
	mi := &file_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusReply) ProtoMessage() {}

func (x *GetNotificationStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusReply.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusReply) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *GetNotificationStatusReply) GetStatuses() []*GetNotificationStatusReply_StatusPerChannel {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type GetNotificationStatusReply_StatusPerChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       NotificationChannel    `protobuf:"varint,1,opt,name=channel,proto3,enum=teller.v1.NotificationChannel" json:"channel,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=teller.v1.NotificationStatus" json:"status,omitempty"`
	FailReason    *string                `protobuf:"bytes,3,opt,name=fail_reason,json=failReason,proto3,oneof" json:"fail_reason,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationStatusReply_StatusPerChannel) Reset() {
	*x = GetNotificationStatusReply_StatusPerChannel{}
	mi := &file_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusReply_StatusPerChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusReply_StatusPerChannel) ProtoMessage() {}

func (x *GetNotificationStatusReply_StatusPerChannel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusReply_StatusPerChannel.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusReply_StatusPerChannel) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetNotificationStatusReply_StatusPerChannel) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NotificationChannel_Unknown
}

func (x *GetNotificationStatusReply_StatusPerChannel) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NotificationStatus_Unknown
}

func (x *GetNotificationStatusReply_StatusPerChannel) GetFailReason() string {
	if x != nil && x.FailReason != nil {
		return *x.FailReason
	}
	return ""
}

func (x *GetNotificationStatusReply_StatusPerChannel) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_v1_notification_proto protoreflect.FileDescriptor

const file_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\x15v1/notification.proto\x12\tteller.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x9c\x02\n" +
	"\fNotification\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x05title\x12\x1e\n" +
	"\x04body\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x90NR\x04body\x12 \n" +
	"\x06ref_id\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x05refId\x12K\n" +
	"\bchannels\x18\x04 \x03(\x0e2\x1e.teller.v1.NotificationChannelB\x0f\xfaB\f\x92\x01\t\"\a\x82\x01\x04\x18\x01\x18\x02R\bchannels\x12K\n" +
	"\vschedule_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02@\x01H\x00R\vschedule_at\x88\x01\x01B\x0e\n" +
	"\f_schedule_at\"\xb4\x02\n" +
	"\x10StatusPerChannel\x12D\n" +
	"\achannel\x18\x01 \x01(\x0e2\x1e.teller.v1.NotificationChannelB\n" +
	"\xfaB\a\x82\x01\x04\x18\x01\x18\x02R\achannel\x12C\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.teller.v1.NotificationStatusB\f\xfaB\t\x82\x01\x06\x18\x01\x18\x02\x18\x03R\x06status\x120\n" +
	"\vfail_reason\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xe8\aH\x00R\n" +
	"failReason\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01B\x0e\n" +
	"\f_fail_reasonB\x0f\n" +
	"\r_completed_at\"8\n" +
	"\rWillPushReply\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"O\n" +
	"\x10BoardcastRequest\x12;\n" +
	"\fnotification\x18\x01 \x01(\v2\x17.teller.v1.NotificationR\fnotification\"\x88\x01\n" +
	"\x12ChannelDestination\x12D\n" +
	"\achannel\x18\x01 \x01(\x0e2\x1e.teller.v1.NotificationChannelB\n" +
	"\xfaB\a\x82\x01\x04\x18\x01\x18\x02R\achannel\x12,\n" +
	"\vdestination\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\vdestination\"\x9d\x01\n" +
	"\x11SendToUserRequest\x12;\n" +
	"\fnotification\x18\x01 \x01(\v2\x17.teller.v1.NotificationR\fnotification\x12K\n" +
	"\fdestinations\x18\x02 \x03(\v2\x1d.teller.v1.ChannelDestinationB\b\xfaB\x05\x92\x01\x02\b\x01R\fdestinations\"Q\n" +
	"\x15BulkSendToUserRequest\x128\n" +
	"\brequests\x18\x01 \x03(\v2\x1c.teller.v1.SendToUserRequestR\brequests\"I\n" +
	"\x13BulkSendToUserReply\x122\n" +
	"\areplies\x18\x01 \x03(\v2\x18.teller.v1.WillPushReplyR\areplies\"R\n" +
	"\x1cGetNotificationStatusRequest\x122\n" +
	"\x0fnotification_id\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x182R\x0enotificationId\"\xa7\x03\n" +
	"\x1aGetNotificationStatusReply\x12R\n" +
	"\bstatuses\x18\x01 \x03(\v26.teller.v1.GetNotificationStatusReply.StatusPerChannelR\bstatuses\x1a\xb4\x02\n" +
	"\x10StatusPerChannel\x12D\n" +
	"\achannel\x18\x01 \x01(\x0e2\x1e.teller.v1.NotificationChannelB\n" +
	"\xfaB\a\x82\x01\x04\x18\x01\x18\x02R\achannel\x12C\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.teller.v1.NotificationStatusB\f\xfaB\t\x82\x01\x06\x18\x01\x18\x02\x18\x03R\x06status\x120\n" +
	"\vfail_reason\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xe8\aH\x00R\n" +
	"failReason\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01B\x0e\n" +
	"\f_fail_reasonB\x0f\n" +
	"\r_completed_at*s\n" +
	"\x13NotificationChannel\x12\x1f\n" +
	"\x1bNotificationChannel_Unknown\x10\x00\x12\x1c\n" +
	"\x18NotificationChannel_Push\x10\x01\x12\x1d\n" +
	"\x19NotificationChannel_Email\x10\x02*\x90\x01\n" +
	"\x12NotificationStatus\x12\x1e\n" +
	"\x1aNotificationStatus_Unknown\x10\x00\x12\x1e\n" +
	"\x1aNotificationStatus_Pending\x10\x01\x12\x1b\n" +
	"\x17NotificationStatus_Sent\x10\x02\x12\x1d\n" +
	"\x19NotificationStatus_Failed\x10\x032\xe2\x02\n" +
	"\x13NotificationService\x12B\n" +
	"\tBoardcast\x12\x1b.teller.v1.BoardcastRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\n" +
	"SendToUser\x12\x1c.teller.v1.SendToUserRequest\x1a\x18.teller.v1.WillPushReply\"\x00\x12T\n" +
	"\x0eBulkSendToUser\x12 .teller.v1.BulkSendToUserRequest\x1a\x1e.teller.v1.BulkSendToUserReply\"\x00\x12i\n" +
	"\x15GetNotificationStatus\x12'.teller.v1.GetNotificationStatusRequest\x1a%.teller.v1.GetNotificationStatusReply\"\x00B;Z9github.com/toeydevelopment/telltheworld/apis/teller/v1;v1b\x06proto3"

var (
	file_v1_notification_proto_rawDescOnce sync.Once
	file_v1_notification_proto_rawDescData []byte
)

func file_v1_notification_proto_rawDescGZIP() []byte {
	file_v1_notification_proto_rawDescOnce.Do(func() {
		file_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_notification_proto_rawDesc), len(file_v1_notification_proto_rawDesc)))
	})
	return file_v1_notification_proto_rawDescData
}

var file_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_notification_proto_goTypes = []any{
	(NotificationChannel)(0),                            // 0: teller.v1.NotificationChannel
	(NotificationStatus)(0),                             // 1: teller.v1.NotificationStatus
	(*Notification)(nil),                                // 2: teller.v1.Notification
	(*StatusPerChannel)(nil),                            // 3: teller.v1.StatusPerChannel
	(*WillPushReply)(nil),                               // 4: teller.v1.WillPushReply
	(*BoardcastRequest)(nil),                            // 5: teller.v1.BoardcastRequest
	(*ChannelDestination)(nil),                          // 6: teller.v1.ChannelDestination
	(*SendToUserRequest)(nil),                           // 7: teller.v1.SendToUserRequest
	(*BulkSendToUserRequest)(nil),                       // 8: teller.v1.BulkSendToUserRequest
	(*BulkSendToUserReply)(nil),                         // 9: teller.v1.BulkSendToUserReply
	(*GetNotificationStatusRequest)(nil),                // 10: teller.v1.GetNotificationStatusRequest
	(*GetNotificationStatusReply)(nil),                  // 11: teller.v1.GetNotificationStatusReply
	(*GetNotificationStatusReply_StatusPerChannel)(nil), // 12: teller.v1.GetNotificationStatusReply.StatusPerChannel
	(*timestamppb.Timestamp)(nil),                       // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                               // 14: google.protobuf.Empty
}
var file_v1_notification_proto_depIdxs = []int32{
	0,  // 0: teller.v1.Notification.channels:type_name -> teller.v1.NotificationChannel
	13, // 1: teller.v1.Notification.schedule_at:type_name -> google.protobuf.Timestamp
	0,  // 2: teller.v1.StatusPerChannel.channel:type_name -> teller.v1.NotificationChannel
	1,  // 3: teller.v1.StatusPerChannel.status:type_name -> teller.v1.NotificationStatus
	13, // 4: teller.v1.StatusPerChannel.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 5: teller.v1.BoardcastRequest.notification:type_name -> teller.v1.Notification
	0,  // 6: teller.v1.ChannelDestination.channel:type_name -> teller.v1.NotificationChannel
	2,  // 7: teller.v1.SendToUserRequest.notification:type_name -> teller.v1.Notification
	6,  // 8: teller.v1.SendToUserRequest.destinations:type_name -> teller.v1.ChannelDestination
	7,  // 9: teller.v1.BulkSendToUserRequest.requests:type_name -> teller.v1.SendToUserRequest
	4,  // 10: teller.v1.BulkSendToUserReply.replies:type_name -> teller.v1.WillPushReply
	12, // 11: teller.v1.GetNotificationStatusReply.statuses:type_name -> teller.v1.GetNotificationStatusReply.StatusPerChannel
	0,  // 12: teller.v1.GetNotificationStatusReply.StatusPerChannel.channel:type_name -> teller.v1.NotificationChannel
	1,  // 13: teller.v1.GetNotificationStatusReply.StatusPerChannel.status:type_name -> teller.v1.NotificationStatus
	13, // 14: teller.v1.GetNotificationStatusReply.StatusPerChannel.completed_at:type_name -> google.protobuf.Timestamp
	5,  // 15: teller.v1.NotificationService.Boardcast:input_type -> teller.v1.BoardcastRequest
	7,  // 16: teller.v1.NotificationService.SendToUser:input_type -> teller.v1.SendToUserRequest
	8,  // 17: teller.v1.NotificationService.BulkSendToUser:input_type -> teller.v1.BulkSendToUserRequest
	10, // 18: teller.v1.NotificationService.GetNotificationStatus:input_type -> teller.v1.GetNotificationStatusRequest
	14, // 19: teller.v1.NotificationService.Boardcast:output_type -> google.protobuf.Empty
	4,  // 20: teller.v1.NotificationService.SendToUser:output_type -> teller.v1.WillPushReply
	9,  // 21: teller.v1.NotificationService.BulkSendToUser:output_type -> teller.v1.BulkSendToUserReply
	11, // 22: teller.v1.NotificationService.GetNotificationStatus:output_type -> teller.v1.GetNotificationStatusReply
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_notification_proto_init() }
func file_v1_notification_proto_init() {
	if File_v1_notification_proto != nil {
		return
	}
	file_v1_notification_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_notification_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_notification_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_notification_proto_rawDesc), len(file_v1_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_notification_proto_goTypes,
		DependencyIndexes: file_v1_notification_proto_depIdxs,
		EnumInfos:         file_v1_notification_proto_enumTypes,
		MessageInfos:      file_v1_notification_proto_msgTypes,
	}.Build()
	File_v1_notification_proto = out.File
	file_v1_notification_proto_goTypes = nil
	file_v1_notification_proto_depIdxs = nil
}
