// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/notification.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Notification with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Notification) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Notification with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NotificationMultiError, or
// nil if none found.
func (m *Notification) ValidateAll() error {
	return m.validate(true)
}

func (m *Notification) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetTitle()); l < 1 || l > 255 {
		err := NotificationValidationError{
			field:  "Title",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetBody()); l < 1 || l > 10000 {
		err := NotificationValidationError{
			field:  "Body",
			reason: "value length must be between 1 and 10000 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetRefId()); l < 1 || l > 50 {
		err := NotificationValidationError{
			field:  "RefId",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetChannels() {
		_, _ = idx, item

		if _, ok := _Notification_Channels_InLookup[item]; !ok {
			err := NotificationValidationError{
				field:  fmt.Sprintf("Channels[%v]", idx),
				reason: "value must be in list [1 2]",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.ScheduleAt != nil {

		if t := m.GetScheduleAt(); t != nil {
			ts, err := t.AsTime(), t.CheckValid()
			if err != nil {
				err = NotificationValidationError{
					field:  "ScheduleAt",
					reason: "value is not a valid timestamp",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			} else {

				now := time.Now()

				if ts.Sub(now) <= 0 {
					err := NotificationValidationError{
						field:  "ScheduleAt",
						reason: "value must be greater than now",
					}
					if !all {
						return err
					}
					errors = append(errors, err)
				}

			}
		}

	}

	if len(errors) > 0 {
		return NotificationMultiError(errors)
	}

	return nil
}

// NotificationMultiError is an error wrapping multiple validation errors
// returned by Notification.ValidateAll() if the designated constraints aren't met.
type NotificationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NotificationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NotificationMultiError) AllErrors() []error { return m }

// NotificationValidationError is the validation error returned by
// Notification.Validate if the designated constraints aren't met.
type NotificationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NotificationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NotificationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NotificationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NotificationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NotificationValidationError) ErrorName() string { return "NotificationValidationError" }

// Error satisfies the builtin error interface
func (e NotificationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotification.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NotificationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NotificationValidationError{}

var _Notification_Channels_InLookup = map[NotificationChannel]struct{}{
	1: {},
	2: {},
}

// Validate checks the field values on StatusPerChannel with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StatusPerChannel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StatusPerChannel with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StatusPerChannelMultiError, or nil if none found.
func (m *StatusPerChannel) ValidateAll() error {
	return m.validate(true)
}

func (m *StatusPerChannel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _StatusPerChannel_Channel_InLookup[m.GetChannel()]; !ok {
		err := StatusPerChannelValidationError{
			field:  "Channel",
			reason: "value must be in list [NotificationChannel_Push NotificationChannel_Email]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _StatusPerChannel_Status_InLookup[m.GetStatus()]; !ok {
		err := StatusPerChannelValidationError{
			field:  "Status",
			reason: "value must be in list [NotificationStatus_Pending NotificationStatus_Sent NotificationStatus_Failed]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.FailReason != nil {

		if l := utf8.RuneCountInString(m.GetFailReason()); l < 1 || l > 1000 {
			err := StatusPerChannelValidationError{
				field:  "FailReason",
				reason: "value length must be between 1 and 1000 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.CompletedAt != nil {

		if all {
			switch v := interface{}(m.GetCompletedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, StatusPerChannelValidationError{
						field:  "CompletedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, StatusPerChannelValidationError{
						field:  "CompletedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return StatusPerChannelValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return StatusPerChannelMultiError(errors)
	}

	return nil
}

// StatusPerChannelMultiError is an error wrapping multiple validation errors
// returned by StatusPerChannel.ValidateAll() if the designated constraints
// aren't met.
type StatusPerChannelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StatusPerChannelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StatusPerChannelMultiError) AllErrors() []error { return m }

// StatusPerChannelValidationError is the validation error returned by
// StatusPerChannel.Validate if the designated constraints aren't met.
type StatusPerChannelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StatusPerChannelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StatusPerChannelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StatusPerChannelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StatusPerChannelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StatusPerChannelValidationError) ErrorName() string { return "StatusPerChannelValidationError" }

// Error satisfies the builtin error interface
func (e StatusPerChannelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStatusPerChannel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StatusPerChannelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StatusPerChannelValidationError{}

var _StatusPerChannel_Channel_InLookup = map[NotificationChannel]struct{}{
	1: {},
	2: {},
}

var _StatusPerChannel_Status_InLookup = map[NotificationStatus]struct{}{
	1: {},
	2: {},
	3: {},
}

// Validate checks the field values on WillPushReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WillPushReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WillPushReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WillPushReplyMultiError, or
// nil if none found.
func (m *WillPushReply) ValidateAll() error {
	return m.validate(true)
}

func (m *WillPushReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NotificationId

	if len(errors) > 0 {
		return WillPushReplyMultiError(errors)
	}

	return nil
}

// WillPushReplyMultiError is an error wrapping multiple validation errors
// returned by WillPushReply.ValidateAll() if the designated constraints
// aren't met.
type WillPushReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WillPushReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WillPushReplyMultiError) AllErrors() []error { return m }

// WillPushReplyValidationError is the validation error returned by
// WillPushReply.Validate if the designated constraints aren't met.
type WillPushReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WillPushReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WillPushReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WillPushReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WillPushReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WillPushReplyValidationError) ErrorName() string { return "WillPushReplyValidationError" }

// Error satisfies the builtin error interface
func (e WillPushReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWillPushReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WillPushReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WillPushReplyValidationError{}

// Validate checks the field values on BoardcastRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BoardcastRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BoardcastRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BoardcastRequestMultiError, or nil if none found.
func (m *BoardcastRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BoardcastRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetNotification()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BoardcastRequestValidationError{
					field:  "Notification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BoardcastRequestValidationError{
					field:  "Notification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNotification()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BoardcastRequestValidationError{
				field:  "Notification",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BoardcastRequestMultiError(errors)
	}

	return nil
}

// BoardcastRequestMultiError is an error wrapping multiple validation errors
// returned by BoardcastRequest.ValidateAll() if the designated constraints
// aren't met.
type BoardcastRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BoardcastRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BoardcastRequestMultiError) AllErrors() []error { return m }

// BoardcastRequestValidationError is the validation error returned by
// BoardcastRequest.Validate if the designated constraints aren't met.
type BoardcastRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BoardcastRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BoardcastRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BoardcastRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BoardcastRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BoardcastRequestValidationError) ErrorName() string { return "BoardcastRequestValidationError" }

// Error satisfies the builtin error interface
func (e BoardcastRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBoardcastRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BoardcastRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BoardcastRequestValidationError{}

// Validate checks the field values on ChannelDestination with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ChannelDestination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChannelDestination with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChannelDestinationMultiError, or nil if none found.
func (m *ChannelDestination) ValidateAll() error {
	return m.validate(true)
}

func (m *ChannelDestination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _ChannelDestination_Channel_InLookup[m.GetChannel()]; !ok {
		err := ChannelDestinationValidationError{
			field:  "Channel",
			reason: "value must be in list [NotificationChannel_Push NotificationChannel_Email]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetDestination()); l < 1 || l > 255 {
		err := ChannelDestinationValidationError{
			field:  "Destination",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ChannelDestinationMultiError(errors)
	}

	return nil
}

// ChannelDestinationMultiError is an error wrapping multiple validation errors
// returned by ChannelDestination.ValidateAll() if the designated constraints
// aren't met.
type ChannelDestinationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChannelDestinationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChannelDestinationMultiError) AllErrors() []error { return m }

// ChannelDestinationValidationError is the validation error returned by
// ChannelDestination.Validate if the designated constraints aren't met.
type ChannelDestinationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChannelDestinationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChannelDestinationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChannelDestinationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChannelDestinationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChannelDestinationValidationError) ErrorName() string {
	return "ChannelDestinationValidationError"
}

// Error satisfies the builtin error interface
func (e ChannelDestinationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChannelDestination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChannelDestinationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChannelDestinationValidationError{}

var _ChannelDestination_Channel_InLookup = map[NotificationChannel]struct{}{
	1: {},
	2: {},
}

// Validate checks the field values on SendToUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendToUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendToUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendToUserRequestMultiError, or nil if none found.
func (m *SendToUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendToUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetNotification()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendToUserRequestValidationError{
					field:  "Notification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendToUserRequestValidationError{
					field:  "Notification",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNotification()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendToUserRequestValidationError{
				field:  "Notification",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetDestinations()) < 1 {
		err := SendToUserRequestValidationError{
			field:  "Destinations",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetDestinations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SendToUserRequestValidationError{
						field:  fmt.Sprintf("Destinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SendToUserRequestValidationError{
						field:  fmt.Sprintf("Destinations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SendToUserRequestValidationError{
					field:  fmt.Sprintf("Destinations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SendToUserRequestMultiError(errors)
	}

	return nil
}

// SendToUserRequestMultiError is an error wrapping multiple validation errors
// returned by SendToUserRequest.ValidateAll() if the designated constraints
// aren't met.
type SendToUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendToUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendToUserRequestMultiError) AllErrors() []error { return m }

// SendToUserRequestValidationError is the validation error returned by
// SendToUserRequest.Validate if the designated constraints aren't met.
type SendToUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendToUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendToUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendToUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendToUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendToUserRequestValidationError) ErrorName() string {
	return "SendToUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendToUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendToUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendToUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendToUserRequestValidationError{}

// Validate checks the field values on BulkSendToUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BulkSendToUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BulkSendToUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BulkSendToUserRequestMultiError, or nil if none found.
func (m *BulkSendToUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BulkSendToUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRequests() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BulkSendToUserRequestValidationError{
						field:  fmt.Sprintf("Requests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BulkSendToUserRequestValidationError{
						field:  fmt.Sprintf("Requests[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BulkSendToUserRequestValidationError{
					field:  fmt.Sprintf("Requests[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BulkSendToUserRequestMultiError(errors)
	}

	return nil
}

// BulkSendToUserRequestMultiError is an error wrapping multiple validation
// errors returned by BulkSendToUserRequest.ValidateAll() if the designated
// constraints aren't met.
type BulkSendToUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BulkSendToUserRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BulkSendToUserRequestMultiError) AllErrors() []error { return m }

// BulkSendToUserRequestValidationError is the validation error returned by
// BulkSendToUserRequest.Validate if the designated constraints aren't met.
type BulkSendToUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BulkSendToUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BulkSendToUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BulkSendToUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BulkSendToUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BulkSendToUserRequestValidationError) ErrorName() string {
	return "BulkSendToUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BulkSendToUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBulkSendToUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BulkSendToUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BulkSendToUserRequestValidationError{}

// Validate checks the field values on BulkSendToUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BulkSendToUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BulkSendToUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BulkSendToUserReplyMultiError, or nil if none found.
func (m *BulkSendToUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *BulkSendToUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetReplies() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BulkSendToUserReplyValidationError{
						field:  fmt.Sprintf("Replies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BulkSendToUserReplyValidationError{
						field:  fmt.Sprintf("Replies[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BulkSendToUserReplyValidationError{
					field:  fmt.Sprintf("Replies[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return BulkSendToUserReplyMultiError(errors)
	}

	return nil
}

// BulkSendToUserReplyMultiError is an error wrapping multiple validation
// errors returned by BulkSendToUserReply.ValidateAll() if the designated
// constraints aren't met.
type BulkSendToUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BulkSendToUserReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BulkSendToUserReplyMultiError) AllErrors() []error { return m }

// BulkSendToUserReplyValidationError is the validation error returned by
// BulkSendToUserReply.Validate if the designated constraints aren't met.
type BulkSendToUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BulkSendToUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BulkSendToUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BulkSendToUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BulkSendToUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BulkSendToUserReplyValidationError) ErrorName() string {
	return "BulkSendToUserReplyValidationError"
}

// Error satisfies the builtin error interface
func (e BulkSendToUserReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBulkSendToUserReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BulkSendToUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BulkSendToUserReplyValidationError{}

// Validate checks the field values on GetNotificationStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetNotificationStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetNotificationStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetNotificationStatusRequestMultiError, or nil if none found.
func (m *GetNotificationStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNotificationStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetNotificationId()); l < 1 || l > 50 {
		err := GetNotificationStatusRequestValidationError{
			field:  "NotificationId",
			reason: "value length must be between 1 and 50 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetNotificationStatusRequestMultiError(errors)
	}

	return nil
}

// GetNotificationStatusRequestMultiError is an error wrapping multiple
// validation errors returned by GetNotificationStatusRequest.ValidateAll() if
// the designated constraints aren't met.
type GetNotificationStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNotificationStatusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNotificationStatusRequestMultiError) AllErrors() []error { return m }

// GetNotificationStatusRequestValidationError is the validation error returned
// by GetNotificationStatusRequest.Validate if the designated constraints
// aren't met.
type GetNotificationStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNotificationStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNotificationStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNotificationStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNotificationStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNotificationStatusRequestValidationError) ErrorName() string {
	return "GetNotificationStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetNotificationStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNotificationStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNotificationStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNotificationStatusRequestValidationError{}

// Validate checks the field values on GetNotificationStatusReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetNotificationStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetNotificationStatusReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetNotificationStatusReplyMultiError, or nil if none found.
func (m *GetNotificationStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNotificationStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetStatuses() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetNotificationStatusReplyValidationError{
						field:  fmt.Sprintf("Statuses[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetNotificationStatusReplyValidationError{
						field:  fmt.Sprintf("Statuses[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetNotificationStatusReplyValidationError{
					field:  fmt.Sprintf("Statuses[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetNotificationStatusReplyMultiError(errors)
	}

	return nil
}

// GetNotificationStatusReplyMultiError is an error wrapping multiple
// validation errors returned by GetNotificationStatusReply.ValidateAll() if
// the designated constraints aren't met.
type GetNotificationStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNotificationStatusReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNotificationStatusReplyMultiError) AllErrors() []error { return m }

// GetNotificationStatusReplyValidationError is the validation error returned
// by GetNotificationStatusReply.Validate if the designated constraints aren't met.
type GetNotificationStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNotificationStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNotificationStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNotificationStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNotificationStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNotificationStatusReplyValidationError) ErrorName() string {
	return "GetNotificationStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetNotificationStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNotificationStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNotificationStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNotificationStatusReplyValidationError{}

// Validate checks the field values on
// GetNotificationStatusReply_StatusPerChannel with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetNotificationStatusReply_StatusPerChannel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// GetNotificationStatusReply_StatusPerChannel with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// GetNotificationStatusReply_StatusPerChannelMultiError, or nil if none found.
func (m *GetNotificationStatusReply_StatusPerChannel) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNotificationStatusReply_StatusPerChannel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _GetNotificationStatusReply_StatusPerChannel_Channel_InLookup[m.GetChannel()]; !ok {
		err := GetNotificationStatusReply_StatusPerChannelValidationError{
			field:  "Channel",
			reason: "value must be in list [NotificationChannel_Push NotificationChannel_Email]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _GetNotificationStatusReply_StatusPerChannel_Status_InLookup[m.GetStatus()]; !ok {
		err := GetNotificationStatusReply_StatusPerChannelValidationError{
			field:  "Status",
			reason: "value must be in list [NotificationStatus_Pending NotificationStatus_Sent NotificationStatus_Failed]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.FailReason != nil {

		if l := utf8.RuneCountInString(m.GetFailReason()); l < 1 || l > 1000 {
			err := GetNotificationStatusReply_StatusPerChannelValidationError{
				field:  "FailReason",
				reason: "value length must be between 1 and 1000 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.CompletedAt != nil {

		if all {
			switch v := interface{}(m.GetCompletedAt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetNotificationStatusReply_StatusPerChannelValidationError{
						field:  "CompletedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetNotificationStatusReply_StatusPerChannelValidationError{
						field:  "CompletedAt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCompletedAt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetNotificationStatusReply_StatusPerChannelValidationError{
					field:  "CompletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetNotificationStatusReply_StatusPerChannelMultiError(errors)
	}

	return nil
}

// GetNotificationStatusReply_StatusPerChannelMultiError is an error wrapping
// multiple validation errors returned by
// GetNotificationStatusReply_StatusPerChannel.ValidateAll() if the designated
// constraints aren't met.
type GetNotificationStatusReply_StatusPerChannelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNotificationStatusReply_StatusPerChannelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNotificationStatusReply_StatusPerChannelMultiError) AllErrors() []error { return m }

// GetNotificationStatusReply_StatusPerChannelValidationError is the validation
// error returned by GetNotificationStatusReply_StatusPerChannel.Validate if
// the designated constraints aren't met.
type GetNotificationStatusReply_StatusPerChannelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNotificationStatusReply_StatusPerChannelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNotificationStatusReply_StatusPerChannelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNotificationStatusReply_StatusPerChannelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNotificationStatusReply_StatusPerChannelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNotificationStatusReply_StatusPerChannelValidationError) ErrorName() string {
	return "GetNotificationStatusReply_StatusPerChannelValidationError"
}

// Error satisfies the builtin error interface
func (e GetNotificationStatusReply_StatusPerChannelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNotificationStatusReply_StatusPerChannel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNotificationStatusReply_StatusPerChannelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNotificationStatusReply_StatusPerChannelValidationError{}

var _GetNotificationStatusReply_StatusPerChannel_Channel_InLookup = map[NotificationChannel]struct{}{
	1: {},
	2: {},
}

var _GetNotificationStatusReply_StatusPerChannel_Status_InLookup = map[NotificationStatus]struct{}{
	1: {},
	2: {},
	3: {},
}
